/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
import g4p_controls.*;

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:983334:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:983334:

public void dropList2_click1(GDropList source, GEvent event) { //_CODE_:dropList2:490028:
  println("dropList2 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList2:490028:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:487477:
  appc.background(230);
} //_CODE_:window1:487477:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  dropList1 = new GDropList(this, 202, 4, 90, 80, 3, 10);
  dropList1.setItems(loadStrings("list_983334"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  dropList2 = new GDropList(this, 110, 2, 90, 80, 3, 10);
  dropList2.setItems(loadStrings("list_490028"), 0);
  dropList2.addEventHandler(this, "dropList2_click1");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GDropList dropList1; 
GDropList dropList2; 
GWindow window1;
